# ***Hypothesis Testing***

## 1. Cutlets data
* Parameter of interest = d1-d2
* alpha = 0.05

In [ ]:
#importing libraries
import pandas as pd
import numpy as np
from scipy import stats

In [ ]:
#importing dataset
cutlets=pd.read_csv("G:\Data science\ExcelR\Assignments\Cutlets.csv")
cutlets.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [ ]:
unit_A=cutlets.iloc[:,0].values
unit_B=cutlets.iloc[:,1].values
print(unit_A.mean())
print(unit_B.mean())

7.0190914285714285
6.964297142857142


* Null hypothesis=There is no difference in the diameter of the cutlets i.e., their dia are equal.
* Alternate hypothesis=There is a signifacnt difference in the dia of cutlets b/w two units.

In [ ]:
#two tail t-test
stats.ttest_ind(unit_A,unit_B)

Ttest_indResult(statistic=0.7228688704678061, pvalue=0.4722394724599501)

* pvalue>0.05, Fail to reject Null hypothesis or we would be 47% wrong if we reject null hypothesis
* Therefore, we can say that the diameters of two units of cutlets are equal

## 2.LabTAT data
* Parameter of interest = Difference in the avg of TAT report
* We use f-test for the given problem at alpha = 5% significance level

In [ ]:
lab_tat=pd.read_csv("G:\Data science\ExcelR\Assignments\LabTaT.csv")
lab_tat.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

* Null hypothesis= The mean of TAT reports from 4 laboratories are equal
* Alternate=The mean of TAT reports from 4 laboratories are not equal

In [ ]:
#F-test
stats.f_oneway(lab_tat.iloc[:,0], lab_tat.iloc[:,1],lab_tat.iloc[:,2])

F_onewayResult(statistic=81.055779144798, pvalue=9.489467524356218e-30)

* Since, p-value<0.05
* We can conclude that there is significant diff in avg TAT among the different libraries 

# 3.Buyer ratio dataset 

In [ ]:
buy_ratio=pd.read_csv("G:\Data science\ExcelR\Assignments\BuyerRatio.csv")
buy_ratio

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [ ]:
#Converting dataframe to an array with values
arr=buy_ratio.values
print(arr)

[['Males' 50 142 131 70]
 ['Females' 435 1523 1356 750]]


In [ ]:
#Delete object data type Males and Females from first column
array=np.delete(arr,0,1)
print(array)

[[50 142 131 70]
 [435 1523 1356 750]]


### Chi-square test
* Null hypothesis-Male-female buyer ratios are similar (All proportions are equal)
* Alternate=Male-female buyer ratios are different

In [ ]:
from scipy.stats import chi2_contingency
chi2_contingency(array)

(1.5959455386610577,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

* As p-value is greater than alpha(0.05),we fail to reject null hypothesis
or we would be 66% wrong if we reject null hypothesis
* Therefore, we can conclude that the proportions are equal

## 4. Customer order form

In [ ]:
cust_order=pd.read_csv("G:\Data science\ExcelR\Assignments\Costomer+OrderForm.csv")
cust_order.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [ ]:
pd.crosstab(cust_order['Phillippines'],cust_order['Indonesia'])

Indonesia     Defective  Error Free
Phillippines                       
Defective             2          27
Error Free           31         240

In [ ]:
print(cust_order['Phillippines'].value_counts())
print(cust_order['Indonesia'].value_counts())
print(cust_order['Malta'].value_counts())
print(cust_order['India'].value_counts())

Error Free    271
Defective      29
Name: Phillippines, dtype: int64
Error Free    267
Defective      33
Name: Indonesia, dtype: int64
Error Free    269
Defective      31
Name: Malta, dtype: int64
Error Free    280
Defective      20
Name: India, dtype: int64


In [ ]:
cust_data={'Type':['Error Free','Defective'],
           'Phillippines':[271,29],
           'Indonesia':[267,33],
           'Malta':[269,31],
           'India':[280,20]}
cust_data1=pd.DataFrame(cust_data,columns=['Type','Phillippines','Indonesia','Malta','India'])
cust_data1

Type  Phillippines  Indonesia  Malta  India
0  Error Free           271        267    269    280
1   Defective            29         33     31     20

In [ ]:
#Converting dataframe to an array values
cust_arr=cust_data1.values
print(cust_arr)

[['Error Free' 271 267 269 280]
 ['Defective' 29 33 31 20]]


In [ ]:
#Extracting numerical values by deleting the object data type Error Free and Defective from first column
cust_array=np.delete(cust_arr,0,1)
print(cust_array)

[[271 267 269 280]
 [29 33 31 20]]


## Chi-square test
* Null hypothesis-Defective % do not vary among the centres
* Alternate=Defective % varies

In [ ]:
from scipy.stats import chi2_contingency
chi2_contingency(cust_array)

(3.8589606858203545,
 0.2771020991233144,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

* **0.27>0.05, Therefore the defective% remains same**