# ***Hypothesis Testing***

# 1. Cutlets data


**A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.**

* Parameter of interest = d1-d2
* alpha = 0.05

Dataset used: **'Cutlets.csv'**

In [ ]:
#importing libraries
import pandas as pd
import numpy as np
from scipy import stats

In [ ]:
#importing dataset
cutlets=pd.read_csv("G:\Data science\ExcelR\Assignments\Cutlets.csv")
cutlets.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [ ]:
unit_A=cutlets.iloc[:,0].values
unit_B=cutlets.iloc[:,1].values
#Compare the means of two units of cutlet.
print(unit_A.mean())
print(unit_B.mean())

7.0190914285714285
6.964297142857142



Difference between average diameter of cutlet A 7.02cm & cutlet B 6.96cm is 0.06. 

Apply **two sample two tailed test** as there is no data given for the population (Standard deviation). 

* Null hypothesis=There is no significant difference in the diameter of the cutlets i.e., their dia are equal.
* Alternate hypothesis=There is a significant difference in the dia of cutlets b/w two units.

In [ ]:
#two tail t-test
stats.ttest_ind(unit_A,unit_B)

Ttest_indResult(statistic=0.7228688704678061, pvalue=0.4722394724599501)

* pvalue>0.05, Fail to reject Null hypothesis or we would be 47% wrong if we reject null hypothesis
* Therefore, we can say that there is no significant difference in the  diameters of two units of cutlets. 

# 2. LabTAT data



 **A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.**

* Parameter of interest = Difference in the avg of TAT report
* We use **f-test** for the given problem at alpha = 5% significance level

Dataset used: **'LabTAT.csv'**

In [ ]:
#Load the dataset
lab_tat=pd.read_csv("G:\Data science\ExcelR\Assignments\LabTaT.csv")
lab_tat.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

* Null hypothesis= The mean of TAT reports from 4 laboratories are equal
* Alternate hypothesis=The mean of TAT reports from 4 laboratories are not equal

In [ ]:
#F-test
stats.f_oneway(lab_tat.iloc[:,0], lab_tat.iloc[:,1],lab_tat.iloc[:,2])

F_onewayResult(statistic=81.055779144798, pvalue=9.489467524356218e-30)

* Since, p-value<0.05
* We can conclude that there is significant diff in avg TAT among the different laboratories. Therefore, the manager has to take further steps for the better performance of the laboratories. 

# 3.Buyer ratio dataset 


**Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.**

alpha=0.05

Dataset used: **'BuyerRatio.csv'**

In [ ]:
#Load the dataset
buy_ratio=pd.read_csv("G:\Data science\ExcelR\Assignments\BuyerRatio.csv")
buy_ratio

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [ ]:
#Converting dataframe to an array with values
arr=buy_ratio.values
print(arr)

[['Males' 50 142 131 70]
 ['Females' 435 1523 1356 750]]


In [ ]:
#Delete object data type Males and Females from first column
array=np.delete(arr,0,1)
print(array)

[[50 142 131 70]
 [435 1523 1356 750]]


We use **chi2_test** for our hypothesis as there are more than 2 popoulations to compare and the data is categorical.

### Chi-square test
* Null hypothesis-Male-female buyer ratios are similar (All proportions are equal)
* Alternate=Male-female buyer ratios are different

In [ ]:
from scipy.stats import chi2_contingency
chi2_contingency(array)

(1.5959455386610577,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

* As p-value is greater than alpha(0.05),we fail to reject null hypothesis
or we would be 66% wrong if we reject null hypothesis
* Therefore, we can conclude that the buyer ratios are equal among all the regions.

# 4. Customer order form

**TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain % of the customer order forms. Any error in order form renders it defective and has to be reworked before processing. The manager wants to check whether the defective % varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences.**



Since our data is categorical and we have to compare more than two samples, we use Chi2_test.

Dataset used: **"Costomer+OrderForm.csv"**

In [ ]:
#Load the dataset
cust_order=pd.read_csv("G:\Data science\ExcelR\Assignments\Costomer+OrderForm.csv")
cust_order.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [ ]:
pd.crosstab(cust_order['Phillippines'],cust_order['Indonesia'])

Indonesia     Defective  Error Free
Phillippines                       
Defective             2          27
Error Free           31         240

Can't prepare a cross table using cross_tab function for all the 4 centres.

In [ ]:
#Getting the error free and Defective counts from each centre
print(cust_order['Phillippines'].value_counts())
print(cust_order['Indonesia'].value_counts())
print(cust_order['Malta'].value_counts())
print(cust_order['India'].value_counts())

Error Free    271
Defective      29
Name: Phillippines, dtype: int64
Error Free    267
Defective      33
Name: Indonesia, dtype: int64
Error Free    269
Defective      31
Name: Malta, dtype: int64
Error Free    280
Defective      20
Name: India, dtype: int64


In [ ]:
#Creating a cross table
cust_data={'Type':['Error Free','Defective'],
           'Phillippines':[271,29],
           'Indonesia':[267,33],
           'Malta':[269,31],
           'India':[280,20]}
cust_data1=pd.DataFrame(cust_data,columns=['Type','Phillippines','Indonesia','Malta','India'])
cust_data1

Type  Phillippines  Indonesia  Malta  India
0  Error Free           271        267    269    280
1   Defective            29         33     31     20

In [ ]:
#Converting dataframe to an array values
cust_arr=cust_data1.values
print(cust_arr)

[['Error Free' 271 267 269 280]
 ['Defective' 29 33 31 20]]


In [ ]:
#Extracting numerical values by deleting the object data type Error Free and Defective from first column
cust_array=np.delete(cust_arr,0,1)
print(cust_array)

[[271 267 269 280]
 [29 33 31 20]]


## Chi-square test
* Null hypothesis- Defective % do not vary among the centres
* Alternate hypothesis- Defective % varies

In [ ]:
from scipy.stats import chi2_contingency
chi2_contingency(cust_array)

(3.8589606858203545,
 0.2771020991233144,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

* **0.27>0.05, Therefore the defective% remains same**